### ISSUE TITLE
Build windows

### ISSUE THREAD

**Issue by pombredanne** [pombreda/thirdparty#1]
Using mingw cross compiler on travis OR using appveyor

For travis: see https://github.com/SOCI/soci/issues/247 and http://lists.boost.org/Archives/boost/2013/06/204433.php and https://github.com/rouault/gdal_coverage/blob/trunk_mingw/.travis.yml and https://github.com/LuaDist/Repository/issues/77 and https://github.com/mloskot/travis-ci-test/blob/master/.travis.yml

**Comment by pombredanne** [comment]
Couple more pointers:
https://github.com/mingwpy

Or drop windows? https://www.docker.com/products/docker-toolbox
or build on Cygwin: http://www.cygwin.com/ ?
https://github.com/pombredanne/docker-qt5-mingw32
https://github.com/ogrisel/python-winbuilder
https://bitbucket.org/carlkl/

**Comment by pombredanne** [comment]
See also https://github.com/multiarch

**Comment by pombreda** [comment]
We are building with appveyor alright
